[[local-agent]]
path = "/Users/roman/Coral-demo/farringdon-compliance/agents/Coral-Interface-Agent"

[[local-agent]]
path = "/Users/roman/Coral-demo/agents/Coral-FirecrawlMCP-Agent"

[[local-agent]]
path = "/Users/roman/Coral-demo/agents/Coral-ReplicateMCP-Agent"

[[local-agent]]
path = "/Users/roman/Coral-demo/agents/Coral-blogideas-Agent"

